### ISSUE TITLE
NPE when using the putMarkLogic Processor

### ISSUE THREAD

**Issue by scarton** [marklogic/nifi-nars#5]
Using the getFile processor as input, and routing the success path to putMarkLogic, I get the exception below:

2018-09-05 12:29:09,259 ERROR [Timer-Driven Process Thread-6] o.a.n.marklogic.processor.PutMarkLogic PutMarkLogic[id=aa8f272d-0165-1000-e5cf-2f888bb25b14] Failed to process session due to org.apache.nifi.processor.exception.ProcessException: java.lang.NullPointerException: org.apache.nifi.processor.exception.ProcessException: java.lang.NullPointerException
org.apache.nifi.processor.exception.ProcessException: java.lang.NullPointerException
        at org.apache.nifi.marklogic.processor.PutMarkLogic.onTrigger(PutMarkLogic.java:288)
        at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1165)
        at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:203)
        at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.apache.nifi.attribute.expression.language.StandardPropertyValue.isExpressionLanguagePresent(StandardPropertyValue.java:204)
        at org.apache.nifi.marklogic.processor.PutMarkLogic.buildWriteEvent(PutMarkLogic.java:347)
        at org.apache.nifi.marklogic.processor.PutMarkLogic.onTrigger(PutMarkLogic.java:312)
        at org.apache.nifi.marklogic.processor.PutMarkLogic.onTrigger(PutMarkLogic.java:284)
        ... 10 common frames omitted

**Comment by scarton** [comment]
![image](https://user-images.githubusercontent.com/1399942/45107850-e84cc480-b108-11e8-87ce-379b89c828ad.png)

**Comment by scarton** [comment]
![image](https://user-images.githubusercontent.com/1399942/45107934-2a760600-b109-11e8-87b0-b03bc0a75340.png)

**Comment by MatthewGordonSmith** [comment]
I have found that you will always get a NullPointerException if you don't add at least one collection in your PutMarkLogic processor properties (4th one down). I think this is a bug but a descriptive collection name isn't the worst addition to your data anyway :-)

**Comment by scarton** [comment]
Thanks - and I agree. Was just trying to get this working to test a processor I'm developing that will feed data into it. I'll add a  collection name for now until there's a fix.
